# Generated by Django 4.0.4 on 2022-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='statement',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase3',
            field=models.TextField(),
        ),
    ]
