# Generated by Django 4.0.4 on 2022-06-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_remove_problem_statement_problem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
