# Generated by Django 4.0.4 on 2022-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_problem_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testcase1',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testcase2',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testcase3',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='testcase',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
