# Generated by Django 4.0.4 on 2022-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_remove_problem_answer1_remove_problem_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdictCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=100),
        ),
    ]
