# Generated by Django 4.0.4 on 2022-06-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_submission_verdictcode_alter_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.FileField(upload_to='answers/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcase',
            field=models.FileField(upload_to='testcases/% Y/% m/% d/'),
        ),
    ]
